services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data

# añadir estas líneas al final del archivo para proxy inverso 
networks:
  default:
    external: true
    name: proxy